// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using StockLibrary;
using System;

namespace StockLibrary.Migrations
{
    [DbContext(typeof(SqliteContext))]
    [Migration("20171217224239_Delta")]
    partial class Delta
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("StockLibrary.Models.Fund", b =>
                {
                    b.Property<string>("Symbol")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Exchange");

                    b.Property<bool>("IsActive");

                    b.Property<string>("Name");

                    b.HasKey("Symbol");

                    b.ToTable("Fund");
                });

            modelBuilder.Entity("StockLibrary.Models.FundDay", b =>
                {
                    b.Property<int>("FundDayID")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("Close");

                    b.Property<decimal>("Delta");

                    b.Property<DateTime>("FundDayDate");

                    b.Property<decimal>("High");

                    b.Property<decimal>("Low");

                    b.Property<decimal>("Open");

                    b.Property<string>("Symbol");

                    b.HasKey("FundDayID");

                    b.HasIndex("Symbol");

                    b.ToTable("FundDay");
                });

            modelBuilder.Entity("StockLibrary.Models.FundDay", b =>
                {
                    b.HasOne("StockLibrary.Models.Fund", "Fund")
                        .WithMany()
                        .HasForeignKey("Symbol");
                });
#pragma warning restore 612, 618
        }
    }
}
